version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: dev_docker.file
    command: sh -c "cd app && ng serve --host 0.0.0.0"
    ports:
      - "4300:4200"
    depends_on:
      - back
    volumes:
      - type: bind
        source: C:\Users\IPALACIOS\Documents\Docker\tallerDocker\front
        target: /home/angularProject
    networks:
      front_network:
        aliases:
          - front
          - angular
  back:
    build:
      context: ./back
      dockerfile: dev_docker.file
    command: ./gradlew bootRun
    ports:
      - "8380:8380"
    environment:
      - HULK_STORE_HOST=http://localhost:4300
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - type: bind
        source: C:\Users\IPALACIOS\Documents\Docker\tallerDocker\back\taller
        target: /home/javaProject
    networks:
      back_network:
        aliases:
          - back
          - java
      front_network:
        aliases:
          - back
          - java
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=storeDB
    volumes:
      - type: bind
        source: C:\Users\IPALACIOS\Documents\Docker\tallerDocker\bd\
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: hulk_vol
        target: /var/lib/mysql
    networks:
      back_network:
        aliases:
          - mysql
          - database
        
volumes:
  hulk_vol:

networks:
  back_network:
  front_network: